### ISSUE TITLE
Adding Recycle to existing flowsheet-(Methanol-Chloroform)

### ISSUE THREAD

**Issue by RahulNagraj444** [FOSSEE/OMChemSim#9]
[Meth_Wat_Distillation.zip](https://github.com/FOSSEE/OMChemSim/files/3116528/Meth_Wat_Distillation.zip)

**Comment by mehul009** [comment]
Hello Mr. Rahul;
I think think there is unnecessary complexity in your Methanol-Chloroform_Separation.mo simulation's Material stream model. And i think actually it create problem in iteration.
So, just use 

model Material_Streams
  extends Simulator.Streams.Material_Stream;
  extends Simulator.Files.Thermodynamic_Packages.NRTL;
end Material_Streams;

instead of your model.

and i also update methanol water distillation file with your suggested DWSIM simulation.
[updated files.zip](https://github.com/FOSSEE/OMChemSim/files/3144413/updated.files.zip)

**Comment by pravindalve** [comment]
Hello,

The complexity you are mentioning is actually not complexity. Those are the parameter values, which are overridden when we define values of comp and NOC in flowsheet. Main problem is it is not converging when recycle is added without giving start values. I have added some start values and tried. The flowsheet is converging after giving start values but it is giving wrong results and also taking too much time.

**Comment by mehul009** [comment]
Hello,

Actually, I understand that this is parameter but I don't find any other word to define it; 

but I think this start value is inappropriate in case of  bottom1,2 and distillate1,2 because they all require a different value for startup and for that we have to change the startup value inside each material stream's definition, maybe this will help.

but in this case, I try to converge without any kind of start value and it converging with recycling and also provide appropriate result.

And yes it takes much time with my suggestion also (I attach my time statics here)
![time statics](https://user-images.githubusercontent.com/31311720/57235232-0e33bb80-7040-11e9-915b-d7b86cbe8da8.jpg)

**Comment by pravindalve** [comment]
Please share the exported mat or CSV file of your results.

**Comment by mehul009** [comment]
[Pres_swin_Dist.flowsheet_res.zip](https://github.com/FOSSEE/OMChemSim/files/3148725/Pres_swin_Dist.flowsheet_res.zip)

**Comment by pravindalve** [comment]
There are no values in the result file. Please check and then send the file.

**Comment by mehul009** [comment]
[data.zip](https://github.com/FOSSEE/OMChemSim/files/3148907/data.zip)

**Comment by mehul009** [comment]
When i change the path .mat file does not working properly so i try to send you .csv file after words; but i have some doubt in this proposed model

It have to be like this
![image](https://user-images.githubusercontent.com/31311720/57242578-7c34ae80-7051-11e9-890d-38ace570b312.png)

instead of 
![image](https://user-images.githubusercontent.com/31311720/57242633-a8e8c600-7051-11e9-8144-89c09fa0858f.png)

**Comment by mehul009** [comment]
[data_res.zip](https://github.com/FOSSEE/OMChemSim/files/3152320/data_res.zip)
here the csv file for the data, and look the result of bottom 1 and 2 you find negative flowrate but the specification provides by us in the simulation are satisfy.

**Comment by pravindalve** [comment]
This is the problem we are facing. Bottom flowrates are negative as well as distillate vapor fractions are 1 for total condenser. Which is not the right solution. We are also trying to reduce time taken.

**Comment by mehul009** [comment]
> 
> 
> When I change the path .mat file does not working properly so I will try to send you .csv file(possibly tomorrow), but I have some doubt in this proposed model
> 
> It have to be like this
> ![image](https://user-images.githubusercontent.com/31311720/57242578-7c34ae80-7051-11e9-890d-38ace570b312.png)
> 
> instead of
> ![image](https://user-images.githubusercontent.com/31311720/57242633-a8e8c600-7051-11e9-8144-89c09fa0858f.png)

I have one literature for you, please look that. and also see the DWSIM simulation attached. 
[OM.zip](https://github.com/FOSSEE/OMChemSim/files/3152628/OM.zip)

I think there is some problem in our recycle part.

**Comment by pravindalve** [comment]
Both the recycle are right. Please look at the column conditions also from the reference you are giving. One is attractive distillation and other is Pressure Swing Distillation. We are simulating Pressure Swing distillation.
